spring:
  h2:
    console:
      enabled: true
  datasource:
    username: user
    password: password
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./database
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect