spring:
  datasource:
    username: idp_andreas
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://baey.eu/idp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL81Dialect
  main:
    banner-mode: "off"